FROM oracle/graalvm-ce:20.1.0-java11 as graalvm
RUN gu install native-image

COPY . /home/app/hello-world
WORKDIR /home/app/hello-world

RUN native-image --no-server -cp build/libs/hello-world-*-all.jar
EXPOSE 8080
ENTRYPOINT [ "/home/app/hello-world/hello-world" ]